### ISSUE TITLE
Doesn't respond

### ISSUE THREAD

**Issue by proudparrot2** [Lebyy/SmartestChatBot#10]
Hi, I have a Discord bot hooked up to this and it's not responding. I tried running it in a solo script and it doesn't respond either. Any idea what's happening?

Please advise because people who use my bot are asking why it isn't working

**Comment by proudparrot2** [comment]
There is also this huge chunk of error that gets left behind

**Comment by Lebyy** [comment]
Is it possible for you to send me the screenshot of the errors?

**Comment by ririko5834** [comment]
Same error, your api is down 
translate api:
![image](https://user-images.githubusercontent.com/64729293/155728636-9e2243ab-5e59-4276-9875-3e0dff9453e5.png)

https://api.affiliateplus.xyz/
![image](https://user-images.githubusercontent.com/64729293/155728677-838b240a-db17-47ff-a80c-231c093cf428.png)

**Comment by proudparrot2** [comment]
it’s fine I already switched to another API

**Comment by ririko5834** [comment]
> it’s fine I already switched to another API

Can you send me link to new API?

**Comment by proudparrot2** [comment]
https://www.npmjs.com/package/discord-chatbot

**Comment by Lebyy** [comment]
> Same error, your api is down translate api: ![image](https://user-images.githubusercontent.com/64729293/155728636-9e2243ab-5e59-4276-9875-3e0dff9453e5.png)
> 
> https://api.affiliateplus.xyz/ ![image](https://user-images.githubusercontent.com/64729293/155728677-838b240a-db17-47ff-a80c-231c093cf428.png)

About this, the api restarts every hour to clear cookies cache, the translate api isnt owned by me I dont maintain it, lmk if you have a better translate api that could work

**Comment by ririko5834** [comment]
Why I am getting `{"message":"SPAM","error":true}`?
