### ISSUE TITLE
Issuses regarding Owner!

### ISSUE THREAD

**Issue by CrauxDEV0** [Lebyy/SmartestChatBot#14]
I used this package to make Chatbot and I set the owner name to **My Name** but it still says his owner is **Lebyy_De!**
![Screenshot_20220509-114633_Discord](https://user-images.githubusercontent.com/96301244/167351250-550e4771-fcb9-4859-b065-a40dd8da9254.jpg)

It is a bug I think :(
!
Fix this plz :)

**Comment by Lebyy** [comment]
Should be fixed in the latest release! (2.0.3). :D
