### ISSUE TITLE
The chatbot won't respond

### ISSUE THREAD

**Issue by JoeyRainbowZ** [Lebyy/SmartestChatBot#17]
It won't respond :(

**Comment by ServerDeveloper9447** [comment]
Looks like the api is down

**Comment by ririko5834** [comment]
I have the same problem @Lebyy 
![image](https://user-images.githubusercontent.com/64729293/189676007-6968ce4f-c806-4c3f-9fc5-77f2c660c9cf.png)

The API is not working

**Comment by JoeyRainbowZ** [comment]
![image](https://user-images.githubusercontent.com/79990012/189679579-5e59c12d-1bc1-435c-9532-7dac069d5169.png)
I think the discontinued, @Lebyy can you use another API?

**Comment by Lebyy** [comment]
Should be fixed!
