### ISSUE TITLE
How to fix this error

### ISSUE THREAD

**Issue by Xx-Mohit-xX** [Lebyy/SmartestChatBot#8]
![Screenshot_20210710-225732_Samsung Internet.jpg](https://user-images.githubusercontent.com/75924613/125171574-9559bc80-e1d2-11eb-868e-b568203ab197.jpg)

**Comment by Xx-Mohit-xX** [comment]
I am using auto for language

**Comment by Lebyy** [comment]
Hello there! Looks like you got rate limited by the translate api.

**Comment by Xx-Mohit-xX** [comment]
So what should i do

**Comment by LightningBolt62** [comment]
> So what should i do

Wait,Then try again ig
